[package]
name = "infinity_os"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.4"
flanterm = "0.0.2"
spin = "0.9.8"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
x86_64 = "0.14.2"
