name: Makefile CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        target: x86_64-unknown-none
        components: rust-src

    - name: Install xorriso
      run: sudo apt-get update && sudo apt-get install -y xorriso

    - name: Verify xorriso installation
      run: xorriso -version

    - name: Install qemu
      run: sudo apt-get install qemu-system

    - name: Run build
      run: make
