name: Makefile CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install xorriso
      run: sudo apt-get update && sudo apt-get install -y xorriso

    - name: Verify xorriso installation
      run: xorriso -version

    - name: Run build
      run: make
